[default]
; Dial any 2xx extension to call a user's dedicated AI line
exten => _2XX,1,Dial(PJSIP/livekit/sip:${EXTEN}@livekit-sip:5060)
exten => _2XX,n,Hangup()

; Dial any 1xx extension to call a registered softphone/deskphone
exten => _1XX,1,Dial(PJSIP/${EXTEN})
exten => _1XX,n,Hangup()

#include extensions_custom.conf
