exten => 201,1,Dial(PJSIP/livekit/sip:201@10.7.11.141:5060)
exten => 201,n,Hangup()

exten => 202,1,Dial(PJSIP/livekit/sip:202@10.7.11.141:5060)
exten => 202,n,Hangup()

exten => 500,1,Dial(PJSIP/livekit/sip:500@10.7.11.141:5060)
exten => 500,n,Hangup()

exten => 100,1,Dial(PJSIP/100)
exten => 100,n,Hangup()

exten => 101,1,Dial(PJSIP/101)
exten => 101,n,Hangup()

exten => 102,1,Dial(PJSIP/102)
exten => 102,n,Hangup()

exten => 103,1,Dial(PJSIP/103)
exten => 103,n,Hangup()

exten => 104,1,Dial(PJSIP/104)
exten => 104,n,Hangup()

exten => 105,1,Dial(PJSIP/105)
exten => 105,n,Hangup()

exten => 106,1,Dial(PJSIP/106)
exten => 106,n,Hangup()

exten => 107,1,Dial(PJSIP/107)
exten => 107,n,Hangup()

exten => 108,1,Dial(PJSIP/108)
exten => 108,n,Hangup()

exten => 109,1,Dial(PJSIP/109)
exten => 109,n,Hangup()

exten => 110,1,Dial(PJSIP/110)
exten => 110,n,Hangup()
