exten => 201,1,Dial(PJSIP/livekit/sip:201@livekit-sip:5060)
exten => 201,n,Hangup()

exten => 202,1,Dial(PJSIP/livekit/sip:202@livekit-sip:5060)
exten => 202,n,Hangup()

exten => 500,1,Dial(PJSIP/livekit/sip:500@livekit-sip:5060)
exten => 500,n,Hangup()

exten => 1000,1,Dial(PJSIP/livekit/sip:1000@livekit-sip:5060)
exten => 1000,n,Hangup()

exten => 100,1,Dial(PJSIP/100,20)
exten => 100,n,PlayTones(congestion)
exten => 100,n,Wait(3)
exten => 100,n,Hangup()

exten => 101,1,Dial(PJSIP/101,20)
exten => 101,n,PlayTones(congestion)
exten => 101,n,Wait(3)
exten => 101,n,Hangup()

exten => 102,1,Dial(PJSIP/102,20)
exten => 102,n,PlayTones(congestion)
exten => 102,n,Wait(3)
exten => 102,n,Hangup()

exten => 103,1,Dial(PJSIP/103,20)
exten => 103,n,PlayTones(congestion)
exten => 103,n,Wait(3)
exten => 103,n,Hangup()

exten => 104,1,Dial(PJSIP/104,20)
exten => 104,n,PlayTones(congestion)
exten => 104,n,Wait(3)
exten => 104,n,Hangup()

exten => 105,1,Dial(PJSIP/105,20)
exten => 105,n,PlayTones(congestion)
exten => 105,n,Wait(3)
exten => 105,n,Hangup()

exten => 106,1,Dial(PJSIP/106,20)
exten => 106,n,PlayTones(congestion)
exten => 106,n,Wait(3)
exten => 106,n,Hangup()

exten => 107,1,Dial(PJSIP/107,20)
exten => 107,n,PlayTones(congestion)
exten => 107,n,Wait(3)
exten => 107,n,Hangup()

exten => 108,1,Dial(PJSIP/108,20)
exten => 108,n,PlayTones(congestion)
exten => 108,n,Wait(3)
exten => 108,n,Hangup()

exten => 109,1,Dial(PJSIP/109,20)
exten => 109,n,PlayTones(congestion)
exten => 109,n,Wait(3)
exten => 109,n,Hangup()

exten => 110,1,Dial(PJSIP/110,20)
exten => 110,n,PlayTones(congestion)
exten => 110,n,Wait(3)
exten => 110,n,Hangup()

exten => 501,1,Dial(PJSIP/501,20)
exten => 501,n,PlayTones(congestion)
exten => 501,n,Wait(3)
exten => 501,n,Hangup()

exten => 1005,1,Dial(PJSIP/1005,20)
exten => 1005,n,PlayTones(congestion)
exten => 1005,n,Wait(3)
exten => 1005,n,Hangup()

exten => 1006,1,Dial(PJSIP/1006,20)
exten => 1006,n,PlayTones(congestion)
exten => 1006,n,Wait(3)
exten => 1006,n,Hangup()

exten => 1007,1,Dial(PJSIP/1007,20)
exten => 1007,n,PlayTones(congestion)
exten => 1007,n,Wait(3)
exten => 1007,n,Hangup()

exten => 1008,1,Dial(PJSIP/1008,20)
exten => 1008,n,PlayTones(congestion)
exten => 1008,n,Wait(3)
exten => 1008,n,Hangup()
