[global]
type=global

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

; Endpoint for Zoiper (Phone)
[100]
type=endpoint
context=default
disallow=all
allow=ulaw
auth=auth100
aors=100

[auth100]
type=auth
auth_type=userpass
password=secret
username=100

[100]
type=aor
max_contacts=1

; Endpoint for LiveKit SIP Gateway
[livekit]
type=endpoint
context=default
disallow=all
allow=ulaw
aors=livekit

[livekit]
type=aor
contact=sip:livekit-sip:5060
