; Dynamic Transports from Host LAN IP
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=10.7.11.141
external_signaling_address=10.7.11.141
external_signaling_port=5061

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_media_address=10.7.11.141
external_signaling_address=10.7.11.141
external_signaling_port=5061

[10](endpoint-template)
auth=auth10
aors=10
[auth10](auth-template)
username=10
[10](aor-template)

[100](endpoint-template)
auth=auth100
aors=100
[auth100](auth-template)
username=100
[100](aor-template)

[101](endpoint-template)
auth=auth101
aors=101
[auth101](auth-template)
username=101
[101](aor-template)

[102](endpoint-template)
auth=auth102
aors=102
[auth102](auth-template)
username=102
[102](aor-template)

[103](endpoint-template)
auth=auth103
aors=103
[auth103](auth-template)
username=103
[103](aor-template)

[104](endpoint-template)
auth=auth104
aors=104
[auth104](auth-template)
username=104
[104](aor-template)

[105](endpoint-template)
auth=auth105
aors=105
[auth105](auth-template)
username=105
[105](aor-template)

[106](endpoint-template)
auth=auth106
aors=106
[auth106](auth-template)
username=106
[106](aor-template)

[107](endpoint-template)
auth=auth107
aors=107
[auth107](auth-template)
username=107
[107](aor-template)

[108](endpoint-template)
auth=auth108
aors=108
[auth108](auth-template)
username=108
[108](aor-template)

[109](endpoint-template)
auth=auth109
aors=109
[auth109](auth-template)
username=109
[109](aor-template)

[110](endpoint-template)
auth=auth110
aors=110
[auth110](auth-template)
username=110
[110](aor-template)
