[global]
type=global


; Endpoint for LiveKit SIP Gateway
[livekit]
type=endpoint
context=default
disallow=all
allow=ulaw
direct_media=no
rewrite_contact=yes
force_rport=yes
aors=livekit
rtp_timeout=0
rtp_timeout_hold=0
rtp_keepalive=5

[livekit]
type=aor
contact=sip:livekit-sip:5060

[livekit]
type=identify
endpoint=livekit
match=livekit-sip

; --- TEMPLATES ---
[endpoint-template](!)
type=endpoint
context=default
disallow=all
allow=ulaw
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes
direct_media=no
ice_support=yes
rtp_timeout=0
rtp_timeout_hold=0
rtp_keepalive=5

[auth-template](!)
type=auth
auth_type=userpass
password=secret

[aor-template](!)
type=aor
max_contacts=1
remove_existing=no


#include pjsip_custom.conf

