; Dynamic Transports from Host LAN IP
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=10.7.11.141
external_signaling_address=10.7.11.141
external_signaling_port=5061

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_media_address=10.7.11.141
external_signaling_address=10.7.11.141
external_signaling_port=5061

[100](endpoint-template)
auth=auth100
aors=100
[auth100](auth-template)
username=100
[100](aor-template)

[101](endpoint-template)
auth=auth101
aors=101
[auth101](auth-template)
username=101
[101](aor-template)

[102](endpoint-template)
auth=auth102
aors=102
[auth102](auth-template)
username=102
[102](aor-template)

[103](endpoint-template)
auth=auth103
aors=103
[auth103](auth-template)
username=103
[103](aor-template)

[104](endpoint-template)
auth=auth104
aors=104
[auth104](auth-template)
username=104
[104](aor-template)

[105](endpoint-template)
auth=auth105
aors=105
[auth105](auth-template)
username=105
[105](aor-template)

[106](endpoint-template)
auth=auth106
aors=106
[auth106](auth-template)
username=106
[106](aor-template)

[107](endpoint-template)
auth=auth107
aors=107
[auth107](auth-template)
username=107
[107](aor-template)

[108](endpoint-template)
auth=auth108
aors=108
[auth108](auth-template)
username=108
[108](aor-template)

[109](endpoint-template)
auth=auth109
aors=109
[auth109](auth-template)
username=109
[109](aor-template)

[110](endpoint-template)
auth=auth110
aors=110
[auth110](auth-template)
username=110
[110](aor-template)

[501](endpoint-template)
auth=auth501
aors=501
[auth501](auth-template)
username=501
[501](aor-template)

[1005](endpoint-template)
auth=auth1005
aors=1005
[auth1005](auth-template)
username=1005
[1005](aor-template)

[1006](endpoint-template)
auth=auth1006
aors=1006
[auth1006](auth-template)
username=1006
[1006](aor-template)

[1007](endpoint-template)
auth=auth1007
aors=1007
[auth1007](auth-template)
username=1007
[1007](aor-template)

[1008](endpoint-template)
auth=auth1008
aors=1008
[auth1008](auth-template)
username=1008
[1008](aor-template)
